module Threets {
   export var Geometries: any = {
      "WireframeGeometry": WireframeGeometry,
      "ParametricGeometry": ParametricGeometry,
      "ParametricBufferGeometry": ParametricBufferGeometry,
      "TetrahedronGeometry": TetrahedronGeometry,
      "TetrahedronBufferGeometry": TetrahedronBufferGeometry,
      "OctahedronGeometry": OctahedronGeometry,
      "OctahedronBufferGeometry": OctahedronBufferGeometry,
      "IcosahedronGeometry": IcosahedronGeometry,
      "IcosahedronBufferGeometry": IcosahedronBufferGeometry,
      "DodecahedronGeometry": DodecahedronGeometry,
      "DodecahedronBufferGeometry": DodecahedronBufferGeometry,
      "PolyhedronGeometry": PolyhedronGeometry,
      "PolyhedronBufferGeometry": PolyhedronBufferGeometry,
      "TubeGeometry": TubeGeometry,
      "TubeBufferGeometry": TubeBufferGeometry,
      "TorusKnotGeometry": TorusKnotGeometry,
      "TorusKnotBufferGeometry": TorusKnotBufferGeometry,
      "TorusGeometry": TorusGeometry,
      "TorusBufferGeometry": TorusBufferGeometry,
      "TextGeometry": TextGeometry,
      "TextBufferGeometry": TextBufferGeometry,
      "SphereGeometry": SphereGeometry,
      "SphereBufferGeometry": SphereBufferGeometry,
      "RingGeometry": RingGeometry,
      "RingBufferGeometry": RingBufferGeometry,
      "PlaneGeometry": PlaneGeometry,
      "PlaneBufferGeometry": PlaneBufferGeometry,
      "LatheGeometry": LatheGeometry,
      "LatheBufferGeometry": LatheBufferGeometry,
      "ShapeGeometry": ShapeGeometry,
      "ShapeBufferGeometry": ShapeBufferGeometry,
      "ExtrudeGeometry": ExtrudeGeometry,
      "ExtrudeBufferGeometry": ExtrudeBufferGeometry,
      "EdgesGeometry": EdgesGeometry,
      "ConeGeometry": ConeGeometry,
      "ConeBufferGeometry": ConeBufferGeometry,
      "CylinderGeometry": CylinderGeometry,
      "CylinderBufferGeometry": CylinderBufferGeometry,
      "CircleGeometry": CircleGeometry,
      "CircleBufferGeometry": CircleBufferGeometry,
      "BoxGeometry": BoxGeometry,
      "BoxBufferGeometry": BoxBufferGeometry
   }
}
